catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade
packages: []
catalogs:
  build:
    '@intlify/unplugin-vue-i18n': ^11.0.3
    '@shikijs/markdown-it': ^3.20.0
    '@unocss/eslint-config': ^66.5.10
    '@vitejs/plugin-vue': ^6.0.3
    beasties: ^0.3.5
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.54.0
    shiki: ^3.20.0
    unocss: ^66.5.10
    unplugin: ^2.3.11
    unplugin-auto-import: ^20.3.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^29.2.0
    unplugin-vue-router: ^0.19.1
    vite: 8.0.0-beta.3
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.3.3
    vite-plugin-pwa: ^1.2.0
    vite-plugin-vue-devtools: ^8.0.5
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^28.2.2
    vite-ssg-sitemap: ^0.10.0
  dev:
    '@antfu/eslint-config': ^6.7.2
    '@iconify-json/lucide': ^1.2.82
    '@iconify-json/material-symbols': ^1.2.50
    '@iconify-json/solar': ^1.2.5
    '@vue-macros/volar': ^3.1.1
    '@vue/test-utils': ^2.4.6
    cypress: ^15.8.1
    cypress-vite: ^1.8.0
    eslint: ^9.39.2
    eslint-plugin-cypress: ^5.2.0
    eslint-plugin-format: ^1.1.0
    https-localhost: ^4.7.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.9.3
    vitest: ^4.0.16
    vue-tsc: ^3.2.0
  frontend:
    '@unhead/vue': ^2.0.19
    '@unocss/reset': ^66.5.10
    '@vueuse/core': ^14.1.0
    nprogress: ^0.2.0
    pinia: ^3.0.4
    vue: ^3.5.26
    vue-i18n: ^11.2.7
    vue-router: ^4.6.4
  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3
onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
  - unrs-resolver
