packages: []
catalogs:
  build:
    '@intlify/unplugin-vue-i18n': ^6.0.8
    '@shikijs/markdown-it': ^3.4.2
    '@unocss/eslint-config': ^66.1.2
    '@vitejs/plugin-vue': ^5.2.4
    beasties: ^0.3.3
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.41.0
    shiki: ^3.4.2
    unocss: ^66.1.2
    unplugin: ^2.3.4
    unplugin-auto-import: ^19.2.0
    unplugin-vue-components: ^28.5.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^28.3.1
    unplugin-vue-router: ^0.12.0
    vite: ^6.3.5
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.1.0
    vite-plugin-pwa: ^1.0.0
    vite-plugin-vue-devtools: ^7.7.6
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^27.0.1
    vite-ssg-sitemap: ^0.9.0
  dev:
    '@antfu/eslint-config': ^4.13.1
    '@iconify-json/lucide': ^1.2.44
    '@iconify-json/material-symbols': ^1.2.21
    '@iconify-json/solar': ^1.2.2
    '@vue-macros/volar': ^3.0.0-beta.12
    '@vue/test-utils': ^2.4.6
    cypress: ^14.3.3
    cypress-vite: ^1.6.0
    eslint: ^9.27.0
    eslint-plugin-cypress: ^4.3.0
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    lint-staged: ^16.0.0
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    vitest: ^3.1.4
    vue-tsc: ^2.2.10
  frontend:
    '@unhead/vue': ^2.0.9
    '@unocss/reset': ^66.1.2
    '@vueuse/core': ^13.2.0
    nprogress: ^0.2.0
    pinia: ^3.0.2
    vue: ^3.5.14
    vue-i18n: ^11.1.3
    vue-router: ^4.5.1
  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3
onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
  - unrs-resolver
