allowBuilds:
  esbuild: true
  simple-git-hooks: true
catalogMode: strict
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - rollup@2.80.0
catalogs:
  backend:
    '@neteasecloudmusicapienhanced/api': ^4.32.0
    nitro: latest
  build:
    '@iconify-json/lucide': ^1.2.102
    '@iconify-json/material-symbols': ^1.2.67
    '@iconify-json/solar': ^1.2.5
    '@intlify/unplugin-vue-i18n': ^11.1.2
    '@unocss/eslint-config': ^66.6.8
    '@vitejs/plugin-vue': ^6.0.6
    unocss: ^66.6.8
    unocss-preset-shadcn: ^1.0.1
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^32.0.0
    vite: ^8.0.10
    vite-plugin-pwa: ^1.2.0
  dev:
    '@antfu/eslint-config': ^8.2.0
    '@types/node': ^25.6.0
    '@vitest/browser-playwright': ^4.1.5
    '@vue/test-utils': ^2.4.8
    eslint: ^10.2.1
    eslint-plugin-format: ^2.0.1
    jsdom: ^29.0.2
    nano-staged: ^1.0.2
    simple-git-hooks: ^2.13.1
    typescript: ^6.0.3
    vitest: ^4.1.5
    vitest-browser-vue: 2.1.0
    vue-tsc: ^3.2.7
  frontend:
    '@unhead/vue': ^3.0.5
    '@vueuse/core': ^14.2.1
    pinia: ^3.0.4
    vue: 3.6.0-beta.10
    vue-i18n: ^11.4.0
    vue-router: ^5.0.6
