packages: []

catalogs:

  build:
    '@intlify/unplugin-vue-i18n': ^6.0.5
    '@shikijs/markdown-it': ^3.2.2
    '@unocss/eslint-config': ^66.1.0-beta.11
    '@vitejs/plugin-vue': ^5.2.3
    beasties: ^0.3.2
    markdown-it-link-attributes: ^4.0.1
    rollup: ^4.40.0
    shiki: ^3.2.2
    unocss: ^66.1.0-beta.11
    unplugin: ^2.3.2
    unplugin-auto-import: ^19.1.2
    unplugin-vue-components: ^28.5.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-markdown: ^28.3.1
    unplugin-vue-router: ^0.12.0
    vite: ^6.3.1
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-inspect: ^11.0.0
    vite-plugin-pwa: ^1.0.0
    vite-plugin-vue-devtools: ^7.7.5
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^26.1.1
    vite-ssg-sitemap: ^0.8.1

  dev:
    '@antfu/eslint-config': ^4.12.0
    '@iconify-json/lucide': ^1.2.37
    '@iconify-json/material-symbols': ^1.2.19
    '@vue-macros/volar': ^3.0.0-beta.8
    '@vue/test-utils': ^2.4.6
    cypress: ^14.3.0
    cypress-vite: ^1.6.0
    eslint: ^9.24.0
    eslint-plugin-cypress: ^4.2.1
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    lint-staged: ^15.5.1
    simple-git-hooks: ^2.12.1
    taze: ^19.0.4
    typescript: ^5.8.3
    vitest: ^3.1.1
    vue-tsc: ^2.2.8

  frontend:
    '@unhead/vue': ^2.0.8
    '@unocss/reset': ^66.1.0-beta.11
    '@vueuse/core': ^13.1.0
    nprogress: ^0.2.0
    pinia: ^3.0.2
    vue: ^3.5.13
    vue-i18n: ^11.1.3
    vue-router: ^4.5.0

  types:
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/nprogress': ^0.2.3

onlyBuiltDependencies:
  - cypress
  - esbuild
  - simple-git-hooks
